include("shared.lua")
include("sv_config.lua")
include("sv_player.lua")
include("sv_language.lua")
include("sv_message.lua")
include("sv_classmanager.lua")
include("sv_roundmanager.lua")
include("sv_eventmanager.lua")
include("sv_infectionmanager.lua")
include("sv_weaponmanager.lua")
include("sv_extraitems.lua")
include("sv_votemap.lua")

AddCSLuaFile("shared.lua")
AddCSLuaFile("cl_hud.lua")
AddCSLuaFile("cl_language.lua")
AddCSLuaFile("cl_message.lua")
AddCSLuaFile("cl_player.lua")
AddCSLuaFile("cl_roundmanager.lua")
AddCSLuaFile("cl_menu.lua")

function SafeTableRandom(Table)
	local Result = table.Random(Table)
	return Result
end
hook.Add("PlayerDisconnected", "ZombiePlagueDisconnect", function(ply)
	RoundManager:RemovePlayerToPlay(ply)
end)
hook.Add("Initialize", "ServerReady", function()
	Dictionary:SearchLanguages()
	ClassManager:SearchClasses()
	RoundManager:SearchRounds()
	WeaponManager:SearchWeapons()
	ExtraItemsManager:Search()
end)
net.Receive("RequestServerStatus", function(len, ply)
	RoundManager:AddPlayerToPlay(ply)
	
	net.Start("SendServerStatus")
		net.WriteTable(RoundManager:GetServerStatus())
	net.Send(ply)
end)

util.AddNetworkString("OpenZPMenu")
util.AddNetworkString("RequestServerStatus")
util.AddNetworkString("SendServerStatus")
util.AddNetworkString("OpenBackMenu")