ZPClass.Name = "ZombieCrouchClassName"
ZPClass.Description = "ZombieCrouchClassDescription"
ZPClass.MaxHealth = 750
ZPClass.PModel = "models/player/corpse1.mdl"
ZPClass.Speed = 280
ZPClass.RunSpeed = 100
ZPClass.CrouchSpeed = 1.7
ZPClass.Gravity = 0.7
ZPClass.Breath = 50
ClassManager:AddZPClass("CrouchZombie", ZPClass, TEAM_ZOMBIES)