ZPClass.Name = "ZombieLightClassName"
ZPClass.Description = "ZombieLightClassDescription"
ZPClass.MaxHealth = 1000
ZPClass.PModel = "models/player/charple.mdl"
ZPClass.Speed = 290
ZPClass.RunSpeed = 100
ZPClass.CrouchSpeed = 0.4
ZPClass.Gravity = 0.3
ZPClass.Breath = 50
ClassManager:AddZPClass("LightZombie", ZPClass, TEAM_ZOMBIES)