ZPClass.Name = "ZombieSpeedClassName"
ZPClass.Description = "ZombieSpeedClassDescription"
ZPClass.MaxHealth = 750
ZPClass.PModel = "models/player/zombie_fast.mdl"
ZPClass.Speed = 340
ZPClass.RunSpeed = 100
ZPClass.CrouchSpeed = 0.5
ZPClass.Gravity = 0.7
ZPClass.Breath = 250
ClassManager:AddZPClass("SpeedZombie", ZPClass, TEAM_ZOMBIES)