ZPClass.Name = "HumanHeavyClassName"
ZPClass.Description = "HumanHeavyClassDescription"
ZPClass.MaxHealth = 150
ZPClass.Armor = 100
ZPClass.PModel = "models/player/combine_super_soldier.mdl"
ZPClass.Speed = 210
ZPClass.RunSpeed = 100
ZPClass.CrouchSpeed = 0.3
ZPClass.Gravity = 1.2
ZPClass.Battery = 200
ZPClass.Breath = 150
ClassManager:AddZPClass("HeavyHuman", ZPClass, TEAM_HUMANS)