ZPClass.Name = "HumanSpeedClassName"
ZPClass.Description = "HumanSpeedClassDescription"
ZPClass.MaxHealth = 50
ZPClass.Armor = 0
ZPClass.PModel = "models/player/riot.mdl"
ZPClass.Speed = 270
ZPClass.RunSpeed = 100
ZPClass.CrouchSpeed = 0.4
ZPClass.Gravity = 1
ZPClass.JumpPower = 170
ZPClass.Battery = 50
ZPClass.Breath = 150
ClassManager:AddZPClass("SpeedHuman", ZPClass, TEAM_HUMANS)