ZombiesWin=Die Zombies haben die Welt übernommen!
HumansWin=Die Menschen haben die Seuche besiegt!
RoundDraw=Niemand hat gewonnen!
RoundSimple=Die Infektion hat sich ausgebreitet!
RoundSimpleName=Einfacher Infektionsmodus
RoundMultiInfectionName=Mehrfach-Infektionsmodus
RoundNemesisName=Nemesis-Modus
RoundSurvivorName=Überlebender-Modus
RoundSwarmName=Schwarm-Modus
RoundPlagueName=Seuchen-Modus
NoticeFirstZombie=%s ist der erste Zombie!!
NoticeInfect=%s's Gehirn wurde von %s gefressen...
NoticeSelfInfect=%s hat ein T-Virus benutzt!
NoticeAntidote=%s hat ein Gegenmittel benutzt...
NoticeGetCured=%s wurde von %s geheilt...
NoticeNemesis=%s ist ein Nemesis!!!
NoticeSurvivor=%s ist ein Überlebender!!!
NoticeSwarm=Schwarm-Modus!!!
NoticePlague=Seuchen-Modus!
NoticeMultiInfection=Mehrfach-Infektionsmodus!!!
NoticeVotemapEnded=Die Kartenabstimmung ist beendet! %s wird die nächste Karte!
NoticeVotemapProlong=Die aktuelle Karte wird um weitere %s Runde(n) verlängert!
NoticeNotAllowed=Du darfst das jetzt nicht!
NoticeHasHability=Deine Klasse hat eine Fähigkeit! Tippe in der Konsole: zp_ability, um sie zu benutzen!
NoticeIsNotAlive=Du musst am Leben sein, um deine Fähigkeit zu benutzen!
NoticeNoAbility=Deine Klasse hat keine Fähigkeit!
NoticeSpecialClassNotAllowed=Du benutzt eine Spezialklasse, du kannst deine Fähigkeit nicht benutzen!
NoticeNotEnoughAbilityPower=Du hast nicht genug Energie, um deine Fähigkeit zu benutzen!
NoticeForceRound=%s hat %s gestartet
LastZombieLeft=Der letzte Zombie hat verlassen, %s ist der neue Zombie
LastHumanLeft=Der letzte Mensch hat verlassen, %s ist der neue Mensch.
ExtraItemCantBuy=Du kannst dieses Extra-Item gerade nicht kaufen!
ExtraItemEnought=Du hast nicht genug Ammo Packs, um das zu kaufen!
ExtraItemChoose=Du musst ein gültiges Extra-Item wählen!
ExtraItemCantOpen=Du kannst dieses Menü gerade nicht öffnen
ExtraItemBought=Du hast gekauft: '%s'.
AmmoPackWithdraw=Du hast %d Ammo Packs abgehoben, es sind noch %d Ammo Packs in deinem Konto.
AmmoPackDeposit=Du hast %d Ammo Packs eingezahlt, jetzt hast du %d Ammo Packs in deinem Konto.
AmmoPackNotEnought=Nicht genug Geld, Fremder (oder Ammo Packs)!
AmmoPackGivePlyNotFound=Spieler nicht gefunden!
AmmoPackGiveInvalidAmount=Ungültige Menge.
AmmoPackGiveName=%s hat dir %d Ammo Packs gegeben!
AmmoPackTakeName=%s hat dir %d deiner Ammo Packs genommen!
AmmoPackNoAmmoPacks=Dein Konto hat keine Ammo Packs!
AmmoPackBalance=Dein Kontostand beträgt %d Ammo Packs!
AmmoPackPlayerNotFound=Spieler '%s' nicht gefunden!
AmmoPackGiverMessage=Du hast %d an %s gegeben!
CommandInvalidArgument=Ungültiges Argument für diesen Befehl!
CommandNotAccess=Du hast keinen Zugriff auf diesen Befehl!
ExtraItemAntidoteName=Gegenmittel
ExtraItemArmorName=Rüstung
ExtraItemInfectionBombName=Infektionsbombe
ExtraItemGrenadeName=Granate
ExtraItemSlamName=S.L.A.M
ExtraItemTVirusName=T-Virus
ExtraItemZombieMadnessName=Zombie-Wahnsinn
ExtraItemRPGName=RPG
ExtraItemExtraAmmoName=Extra Munition
ExtraItemAntidoteGrenade=Gegenmittel-Granate
RoundsLeft=%d Runde(n) übrig!
FinalRound=Letzte Runde!
SaveSelection=Auswahl speichern?
ClassClass=Klasse
ClassHealth=Gesundheit
ClassArmor=Rüstung
ClassGravity=Schwerkraft
ClassRunSpeed=Laufgeschwindigkeit
ClassSpeed=Geschwindigkeit
ClassBattery=Batterie
ClassAbilityPower=Fähigkeitsenergie
ClassOxygenLevel=Sauerstofflevel
ScoreBoardTitleHumans=Menschen
ScoreBoardTitleZombies=Zombies
ScoreBoardTitleSpectators=Zuschauer
ScoreBoardHeaderName=Name
ScoreBoardHeaderPoints=Punkte
ScoreBoardHeaderKills=Tötungen
ScoreBoardHeaderDeaths=Tode
ScoreBoardHeaderStatus=Status
ScoreBoardHeaderPing=Ping
ScoreBoardStatusSpectating=Zuschauer
ScoreBoardStatusAlive=Am Leben
ScoreBoardStatusDead=Tot
AP=Ammo Packs
MenuZombieChoose=Zombie-Klassenmenü
MenuHumanChoose=Menschenklassenmenü
MenuWeaponChoose=Waffen-Auswahlmenü
MenuPrimaryWeaponChoose=Primärwaffenmenü
MenuSecondaryWeaponChoose=Sekundärwaffenmenü
MenuMeleeWeaponChoose=Nahkampfwaffenmenü
MenuExtraItemChoose=Extra-Items
MenuLanguageChoose=Sprachauswahlmenü
MenuAdminRoundChoose=Rundenauswahlmenü
MenuSpectator=Zuschauer beitreten
MenuNonSpectator=Spielern beitreten
MenuAdmin=Admin-Menü
MenuAdminGiveAmmoPacks=Ammo Packs geben
MenuNoOptionsAvailableNow=Keine Optionen für dieses Menü verfügbar!
MenuBack=Zurück
MenuNext=Weiter
MenuClose=Schließen
MenuCredit=Credits
MenuOptions=Optionen
Nemesis=Nemesis
Survivor=Überlebender
NoticeVotemapProlong=Aktuelle Karte um weitere {RoundsToExtend} Runde(n) verlängern!
HumanDefaultClassName=Mensch
HumanDefaultClassDescription=Ein Mensch, sonst nichts.
HumanHeavyClassName=Schwerer Mensch
HumanHeavyClassDescription=Schütze dich mit seiner Rüstung vor Zombies.
HumanSpeedClassName=Schneller Mensch
HumanSpeedClassDescription=Hat mehr Geschwindigkeit.
HumanCrouchClassName=Hockender Mensch
HumanCrouchClassDescription=Kann beim Ducken schneller laufen.
HumanLightClassName=Leichter Mensch
HumanLightClassDescription=Niedrige Schwerkraft und kein Fallschaden.
HumanCamouflageClassName=Getarnter Mensch
HumanCamouflageClassDescription=Kann sich als Zombie verkleiden.
HumanSuicidalClassName=Suizid-Mensch
HumanSuicidalClassDescription=Ein Mensch, der explodieren kann
ZombieDefaultClassName=Zombie
ZombieDefaultClassDescription=Ein Zombie, sonst nichts.
ZombieHeavyClassName=Schwerer Zombie
ZombieHeavyClassDescription=Eine laufende Wand.
ZombieSpeedClassName=Schneller Zombie
ZombieSpeedClassDescription=Rennt, um Menschen zu finden.
ZombieCrouchClassName=Hockender Zombie
ZombieCrouchClassDescription=Kann beim Ducken schneller laufen.
ZombieLightClassName=Leichter Zombie
ZombieLightClassDescription=Niedrige Schwerkraft und kein Fallschaden.
ZombieLeechClassName=Blutegel-Zombie
ZombieLeechClassDescription=Erhält 500 HP für jeden infizierten Menschen.
ZombieBomberClassName=Bomber-Zombie
ZombieBomberClassDescription=Spawnt mit einer Infektionsbombe.
ZombieCamouflageClassName=Getarnter Zombie
ZombieCamouflageClassDescription=Kann sich als Mensch verkleiden.
ZombieFasterClassName=Schneller Zombie
ZombieFasterClassDescription=Kann schnell sein. Kann auch schwach sein.
ZombieJumperClassName=Springer-Zombie
ZombieJumperClassDescription=Seine Spezialfähigkeit lässt ihn sehr hoch springen.
ZombieTankClassName=Panzer-Zombie
ZombieTankClassDescription=Kann den Gottmodus aktivieren, um sich zu schützen.
HUDCustomizerComboMenu=Menü
HUDCustomizerComboStatusBar=Statusleiste
HUDCustomizerComboRoundTimer=Rundentimer
HUDCustomizerTabTitleBody=Körper
HUDCustomizerTabTitleBorder=Rahmen
HUDCustomizerTabTitleText=Text
HUDCustomizerApplyButton=Übernehmen
HUDCustomizerLabelX=Horizontale Position
HUDCustomizerLabelY=Vertikale Position
HUDCustomizerLabelFont=Schriftart
HUDCustomizerMenu=Menü
HUDCustomizerStatus=Status
HUDCustomizerTimer=Timer
HUDCustomizerTabTitleOther=Weitere Optionen
HUDCustomizerLeft=Links
HUDCustomizerCenter=Mitte
HUDCustomizerRight=Rechts
HUDCustomizerTop=Oben
HUDCustomizerBottom=Unten
HUDSpectatingPlayer=Zuschauer
KeyBindingApply=Übernehmen
KeyBindingCancel=Abbrechen
KeyBindingDefault=Tasten zurücksetzen
KeyBindingKeyAlreadyInUse=Diese Taste wird bereits verwendet
KeyBindingNightVisionToggle=Nachtsicht umschalten
KeyBindingRequestAbility=Klassenfähigkeit benutzen
KeyBindingOpenZPMenu=Zombie-Plague-Menü öffnen
KeyBindingOpenHumanMenu=Menschenklassenmenü öffnen
KeyBindingOpenZombieMenu=Zombie-Klassenmenü öffnen
KeyBindingOpenWeaponsMenu=Waffenmenü öffnen
KeyBindingOpenExtreItemsMenu=Extra-Items-Menü öffnen
KeyBindingPopupTitle=Warnung!
KeyBindingPopupReset=Dies setzt die Tasten auf die Standardwerte zurück, möchtest du fortfahren?
ZPHUDCustomizer=HUD-Anpassungsmenü
ZPKeyBinding=Tastenbelegungsmenü
ZombiePlagueActions=Zombie-Plague-Aktionen
ZombiePlagueMenu=Zombie-Plague-Menüs
ZombiePlagueOptions=Optionsmenü
PopupYes=Ja
PopupNo=Nein
ZPGrenadeExplodeOnHit=Projektil explodiert beim Aufprall
ZPGrenadeArmOnHit=Projektil wird beim Aufprall scharf und explodiert nach %d Sekunde(n)
ZPGrenadeTimeMode=Projektil explodiert %d nach dem Schuss
ExtraItemEX41Name=EX-41
ExtraItemMatadorName=Matador
ExtraItemRPG7Name=RPG-7
ExtraItemHarpoonName=Harpune
ExtraItemM202Name=M202
ExtraItemOrbitalStrikeName=Orbitalangriff
ExtraItemNerveGasName=Nervengas
ExtraItemIEDName=IED
ExtraItemM79GLName=M79 GL
ExtraItemM134Name=M134 Minigun
ExtraItemMilkorMK1Name=Milkor MK1
zp_zombie_footstep_cvar=Zombie-Fußschritte
zp_realistic_mode_cvar=Realistischer Modus
zp_can_hear_death_cvar=Todesgeräusche hören
zp_chat_all_cvar=Globaler Chat
zp_voice_all_cvar=Globaler Sprachchat
zp_min_players_cvar=Minimale Spielerzahl
zp_newround_delay_cvar=Verzögerung vor den Runden
zp_infection_delay_cvar=Verzögerung vor der Infektion
zp_max_rounds_cvar=Runden vor der Abstimmung
zp_round_time_cvar=Rundenzeit
zp_spectate_team_only_cvar=Nur Team beobachten
